#!/bin/sh

export PGDATA=/var/lib/postgresql/data

chmod 700 $PGDATA
chown postgres:postgres $PGDATA

if [ ! -f $PGDATA/postgresql.conf ]; then
    su postgres -c initdb
    echo 'host all all all trust' >>$PGDATA/pg_hba.conf
    cat >$PGDATA/postgresql.conf <<'EOF'
listen_addresses = '0.0.0.0'
fsync = off
EOF

fi

exec su-exec postgres "$@"
